insert into public.head_to_head_stats (
  player_id,
  opponent_id,
  games_played,
  wins,
  losses,
  highest_score,
  total_score,
  average_score,
  upper_bonus_games,
  sucker_games,
  three_of_a_kind_games,
  four_of_a_kind_games,
  full_house_games,
  small_straight_games,
  large_straight_games,
  blowout_wins,
  blowout_losses,
  comeback_wins,
  extra_rolls_used,
  mulligans_used,
  sucker_hunts,
  sucker_hunt_misses,
  sucker_punches_used,
  sucker_punches_received,
  sucker_blockers_used,
  forced_rerolls,
  sucker_tokens_spent,
  average_sucker_tokens_spent,
  sucker_tokens_leftover,
  average_sucker_tokens_leftover
)
select
  player_id,
  opponent_id,
  count(*)::integer as games_played,
  sum(case when won then 1 else 0 end)::integer as wins,
  sum(case when won then 0 else 1 end)::integer as losses,
  max(final_score)::integer as highest_score,
  sum(final_score)::integer as total_score,
  round(avg(final_score)::numeric, 2) as average_score,
  sum(case when upper_bonus_awarded then 1 else 0 end)::integer as upper_bonus_games,
  sum(case when sucker_count > 0 then 1 else 0 end)::integer as sucker_games,
  sum(case when three_of_a_kind_count > 0 then 1 else 0 end)::integer as three_of_a_kind_games,
  sum(case when four_of_a_kind_count > 0 then 1 else 0 end)::integer as four_of_a_kind_games,
  sum(case when full_house_count > 0 then 1 else 0 end)::integer as full_house_games,
  sum(case when small_straight_count > 0 then 1 else 0 end)::integer as small_straight_games,
  sum(case when large_straight_count > 0 then 1 else 0 end)::integer as large_straight_games,
  sum(blowout_win)::integer as blowout_wins,
  sum(blowout_loss)::integer as blowout_losses,
  sum(comeback_win)::integer as comeback_wins,
  sum(extra_rolls_used)::integer as extra_rolls_used,
  sum(mulligans_used)::integer as mulligans_used,
  sum(sucker_hunts)::integer as sucker_hunts,
  sum(sucker_hunt_misses)::integer as sucker_hunt_misses,
  sum(sucker_punches_used)::integer as sucker_punches_used,
  sum(sucker_punches_received)::integer as sucker_punches_received,
  sum(sucker_blockers_used)::integer as sucker_blockers_used,
  sum(forced_rerolls)::integer as forced_rerolls,
  sum(sucker_tokens_spent)::integer as sucker_tokens_spent,
  round(avg(sucker_tokens_spent)::numeric, 2) as average_sucker_tokens_spent,
  sum(sucker_tokens_leftover)::integer as sucker_tokens_leftover,
  round(avg(sucker_tokens_leftover)::numeric, 2) as average_sucker_tokens_leftover
from public.game_player_results
group by player_id, opponent_id
on conflict (player_id, opponent_id) do update set
  games_played = excluded.games_played,
  wins = excluded.wins,
  losses = excluded.losses,
  highest_score = excluded.highest_score,
  total_score = excluded.total_score,
  average_score = excluded.average_score,
  upper_bonus_games = excluded.upper_bonus_games,
  sucker_games = excluded.sucker_games,
  three_of_a_kind_games = excluded.three_of_a_kind_games,
  four_of_a_kind_games = excluded.four_of_a_kind_games,
  full_house_games = excluded.full_house_games,
  small_straight_games = excluded.small_straight_games,
  large_straight_games = excluded.large_straight_games,
  blowout_wins = excluded.blowout_wins,
  blowout_losses = excluded.blowout_losses,
  comeback_wins = excluded.comeback_wins,
  extra_rolls_used = excluded.extra_rolls_used,
  mulligans_used = excluded.mulligans_used,
  sucker_hunts = excluded.sucker_hunts,
  sucker_hunt_misses = excluded.sucker_hunt_misses,
  sucker_punches_used = excluded.sucker_punches_used,
  sucker_punches_received = excluded.sucker_punches_received,
  sucker_blockers_used = excluded.sucker_blockers_used,
  forced_rerolls = excluded.forced_rerolls,
  sucker_tokens_spent = excluded.sucker_tokens_spent,
  average_sucker_tokens_spent = excluded.average_sucker_tokens_spent,
  sucker_tokens_leftover = excluded.sucker_tokens_leftover,
  average_sucker_tokens_leftover = excluded.average_sucker_tokens_leftover,
  updated_at = now();
